### ISSUE TITLE
username : user or real

### ISSUE THREAD

**Issue by id027102** [leibler/dokuwiki-plugin-todo#105]
assigning todo @id027102 username:real or username:user give both the same : user identity not real name, none is ok it gives no name
In dokuwiki user id027102 , Realname : Jean , both gives id027102 in result

**Comment by runout-at** [comment]
duplicate of #98 
see commit https://github.com/leibler/dokuwiki-plugin-todo/commit/49068ecea455ea997d1e4a7adab171ccaf8228e8
included in branch master
