### ISSUE TITLE
Sorting by due date

### ISSUE THREAD

**Issue by Braintelligence** [leibler/dokuwiki-plugin-todo#110]
Hi there!
How do I order `~~TODOLIST showdate:yes~~` by due date?

**Comment by einhirn** [comment]
@leibler @runout-at Any comments on this? Should we go on and merge this?

**Comment by runout-at** [comment]
On Wed, 2020-06-17 at 23:23 -0700, Christian Marg wrote:
> @leibler @runout-at Any comments on this? Should we go on and merge
> this?

ok for me.

i'd prefer to have an option like 'sort:...'
and a configurable default in settings.

but at the moment i'm busy with other stuff...
