### ISSUE TITLE
Position of check box too low

### ISSUE THREAD

**Issue by FloMiLe** [leibler/dokuwiki-plugin-todo#113]
Great plugin, thanks a lot!

Just one thing concerning aesthetics: Would it be possible to raise the check boxes a bit such that they appear roughly in the middle of a line? I attach a screen shot showing that the check box is lower than even the baseline.
<img width="69" alt="Screen Shot 2019-07-19 at 13 07 55" src="https://user-images.githubusercontent.com/13892710/61531190-6b77c000-aa26-11e9-8976-c79c97da256a.png">

**Comment by einhirn** [comment]
I guess that depends on the template used or something else in Wiki setup, because here it looks fine:
![image](https://user-images.githubusercontent.com/189249/74537431-5cb0a780-4f3a-11ea-9b9a-85a4d09643ef.png)

**Comment by einhirn** [comment]
No reply, closing.
