### ISSUE TITLE
Is it possible to view who checked the box?

### ISSUE THREAD

**Issue by LMT1337** [leibler/dokuwiki-plugin-todo#115]

**Comment by runout-at** [comment]
only in the source of your wiki page.
you are welcome to provide a pull request for the feature.
eg for displaying the information in a tool-tip.

i have moved my projects away from github to gitlab [0] for some reasons and doesn't contribute here anymore.

[0] https://gitlab.com/dokuwiki-plugins

**Comment by einhirn** [comment]
Fixed: see #35
