### ISSUE TITLE
SubToDo

### ISSUE THREAD

**Issue by PhilippDobler** [leibler/dokuwiki-plugin-todo#116]
First, I love this plugin! It makes progress much easier!
Is it possible to assign a ToDo to another ToDo.
The Idea would be that the "SubToDo always sticks to its parent but you should still be able to check it individually.
Is it possible to add this feature?

**Comment by einhirn** [comment]
Something like a tree-view widget with checkboxes like in Software installers etc. Feature groups vs. Subfeatures... Currently I neither have an idea nor time to implement something like that.
