### ISSUE TITLE
Links to pages in the root namespace are broken in the page header row when rednered in a namespace

### ISSUE THREAD

**Issue by HuidaeCho** [leibler/dokuwiki-plugin-todo#117]
I have a private namespace where I added `~~TODOLIST~~` to display all TODOs from everywhere. Items from other namespaces are displayed correctly with the correct page heading, but items from the root namespace (no `:` in the page name) render the page header row incorrectly as if those root pages are child pages of the private namespace, not the root namespace.

For example, my namespace and page structure looks like this:
```
/private/start     (~~TODOLIST~~ in this page)
/ns1/start     (<todo>ns1</todo>)
/ns2/start     (<todo>ns2</todo>)
/todo     (<todo>todo</todo>)
```

Now, the TODOLIST table lists these items:
```
----------
ns1:start     <--- this link works
----------
[ ] ns1     <--- this link works
----------
ns2:start     <--- this link works
----------
[ ] ns2     <--- this link works
----------
todo     <--- this link is BROKEN; it links to /private/todo, not to /todo
----------
[ ] todo     <--- this link works
----------
```

I found `syntax/list.php` line 369 uses `$R->internallink()`, which, I think, assumes a relative page ID when there are no colons in the page ID.

OK, it was the global `$ID`. Fixed in PR #118.

**Comment by einhirn** [comment]
> I found |syntax/list.php| line 369 uses |$R->internallink()|, which, I 
> think, assumes a relative page IDs when there are no colons in the page ID.

While I appreciate your bug report, I think your workaround isn't the fix I want to apply to the codebase - I don't understand how or why it works. Can you explain it?

I guess I'd rather find out how to have the search callback return pages in the root name space as ":pagename" instead of "pagename".

Then they'd be rendered fine.

**Comment by HuidaeCho** [comment]
I agree with you that it would be better to always retrieve absolute page names from the beginning. Thanks
