### ISSUE TITLE
<todo> inside <code> is processed by TODOLIST Tag.

### ISSUE THREAD

**Issue by gvauvert** [leibler/dokuwiki-plugin-todo#12]
```
<todo>TODO A</todo>
<code>
<todo>TODO B</todo>
</code>
~~NOCACHE~~
~~TODOLIST~~
```

displays:
[ ]TODO A
[ ]TODO B
instead of :
[ ]TODO A

**Comment by orzechow** [comment]
Any work going on with this issue?

**Comment by runout-at** [comment]
related to #84

**Comment by einhirn** [comment]
> It happens only in some particular cases, for documentation purpose. I am not sure that to slow down and to increase the complexity of the plugin is a good idea.
> Perhaps, you should only mention in the documentation page that this case is not correctly handled for performance reasons.

A pull request to fix this would still be welcome, but until then I've just added a ["Known Issues" Section on the plugins page](https://www.dokuwiki.org/plugin:todo#known_issues).
