### ISSUE TITLE
PHP Warnings when creating an empty TODOLIST

### ISSUE THREAD

**Issue by HuidaeCho** [leibler/dokuwiki-plugin-todo#121]
I had this line:
```
~~TODOLIST ns:todos~~
```
and removed all TODOs from the todos namespace (no TODOs anymore). I got the following warnings:
```
Warning: count(): Parameter must be an array or an object that implements Countable in /home/user/www/dokuwiki/lib/plugins/todo/syntax/list.php on line 322

Warning: Invalid argument supplied for foreach() in /home/user/www/dokuwiki/lib/plugins/todo/syntax/list.php on line 365
```
I believe that `TODOLIST` should support no TODO items.

Thank you!

**Comment by arlt** [comment]
Line number changed but problem persists after updating to the newest version `2022-08-06`.

```
~~TODOLIST ns:test:plugins assigned:arlt~~
```

if nothing is assigned, the page shows an error:

```

TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the todo plugin.

More info has been written to the DokuWiki error log.
```

In `Admin`->`View Logs`->`error` one can see:
```
2022-08-08 05:44:36TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given /var/www/dokuwiki/lib/plugins/todo/syntax/list.php(334)
```

If i remove the box plugin from the plugin folder, the page works again.

Dokuwiki Igor + PHP 7.4 works
Dokuwiki Igor + PHP 8.1 fails

**Comment by arlt** [comment]
Appending
```
$todopages = (array) $todopages;
```
as first lin the the `private function filterpages` seems to fix the problem but i am not a php developer.

You return `$pages` or `null` - maybe this can be a problem in other constellations, too. Maybe using/returning an empty array would be reasonable?! -> Cleaning up the `return` lines, too?!

```js
    332     private function filterpages($todopages, $data) {
    333         $todopages = (array) $todopages;
    334         $pages = array();
    335         if(count($todopages)>0) { 
    336             foreach($todopages as $page) {
    337                 $todos = array();
    338                 // contains 3 arrays: an array with complete matches and 2 arrays with subpatterns
    339                 foreach($page['matches'][1] as $todoindex => $todomatch) {
    340                     $todo = array_merge(array('todotitle' => trim($page['matches'][2][$todoindex]),  'todoindex' => $todoindex), $this->parseTodoArgs($todomatch), $data);
    341 
    342                     if($this->isRequestedTodo($todo)) { $todos[] = $todo; }
    343                 }
    344                 if(count($todos) > 0) {
    345                     $pages[] = array('id' => $page['id'], 'todos' => $todos);
    346                 }
    347             }
    348         }   
    349         return $pages;
    350     }
```

**Comment by runout-at** [comment]
@arlt could you please test if following would work:
` if(isset($todopages) && count($todopages)>0) {`

Maybe we have this problem on other places too.

**Comment by arlt** [comment]
> ` if(isset($todopages) && count($todopages)>0) {`

@runout-at Works here. I tested the code from the first post in this issue, too.

**Comment by runout-at** [comment]
I just did a commit to the master branch which tries to fix similar code in other functions too. This is still completely untested.

@arlt please could you test this too. thanks a lot!

**Comment by arlt** [comment]
@runout-at Works!

Don't forget to:
- update `plugin.info.txt`
- Build new stable archive
- Update Dokuwiki compatibility info for `Igor`: https://www.dokuwiki.org/plugin:todo

Thanks!
