### ISSUE TITLE
Setting 'plugin»todo»Checkbox' has no effect anymore

### ISSUE THREAD

**Issue by FloMiLe** [leibler/dokuwiki-plugin-todo#122]
I don't know since exactly when, but since recently the setting 'plugin»todo»Checkbox' has no effect anymore. While it was possible to hide the checkboxes from todos in lists, they now appear no matter that setting.

Is it possible that something was broking in an update in that regard?

**Comment by FloMiLe** [comment]
This issue still persists. 

I was worried that this might be a side effect of my tampering or interaction with other extensions. But I can confirm it also exists in a completely fresh installation of dokuwiki with only this additional extension installed.

**Comment by einhirn** [comment]
Can you please check whether 84aeaf855befc2ce8d479d8f3a6751edbe1a5659 caused this?

**Comment by FloMiLe** [comment]
Yes, unfortunately, it does not seem the case. Deleting the added string does not make the checkboxes disappear.

**Comment by FloMiLe** [comment]
I'm sorry, I just found in my own documentation that I had disabled the checkboxes manually:
I changed line 311 in _/lib/plugins/todo/syntax/todo.php_ from

    $return = '<input type="checkbox" class="todocheckbox"'

to

    $return = '<input type="checkbox" class="todocheckbox" style="display:none"'

So the feature of hiding the checkboxes in lists had not worked beforehand either. And my tweaking was overwritten by the update...
