### ISSUE TITLE
Hogfather - not compatible

### ISSUE THREAD

**Issue by ccastello** [leibler/dokuwiki-plugin-todo#124]
The plugin is not compatible with the _Hogfather_ version : syntax error on functions "handler" and "render"

**Comment by einhirn** [comment]
which PHP version do you have? Can you send the complete error messages, please?

**Comment by ccastello** [comment]
PHP 7.3
The new syntax of SyntaxPlugin are now :
abstract public function handle($match, $state, $pos, Doku_Handler $handler);
abstract public function render($format, Doku_Renderer $renderer, $data);

**Comment by einhirn** [comment]
There seems to have been a fix in Hogfather RC3, let's try and see whether that helps here, too? The other issue concerning this was closed successfully...

**Comment by ccastello** [comment]
Le 18/06/2020 à 08:28, Christian Marg a écrit :
> There seems to have been a fix in Hogfather RC3, let's try and see
> whether that helps here, too? The other issue concerning this was closed
> successfully...
> 
Hi.
That's ok: the plugin works again. It's fully fonctionnal with hogfather.

**Comment by einhirn** [comment]
Thanks for the feedback!
