### ISSUE TITLE
Feature request: "add todo" tag

### ISSUE THREAD

**Issue by stuporfly** [leibler/dokuwiki-plugin-todo#125]
I would love to have the ability to add a todo-item without having to hit "edit" first - basically, something like a `<Todo-Add/>` tag, which, when rendered,  is replaced by a textfield and an "add todo" button. 

When I enter text, and hit the button, a new todo item is added just above (or below) the todo-add tag, in the DokuWiki page.

**Comment by einhirn** [comment]
Maybe you or someone else will send a PR, I don't see me implementing this.

**Comment by cjohnsonuk** [comment]
Can this functionality be achieved using a bureaucracy form to add content to the same page using pagemod action? Thought this might help in the interim

**Comment by einhirn** [comment]
Should be doable. Can you write up an example? I used something similar in the past, but I'd have to dig it up to produce an example.

**Comment by cjohnsonuk** [comment]
I'd have to start from scratch! There are some good examples of how to update a page on the pagemod page https://www.dokuwiki.org/plugin:pagemod

**Comment by einhirn** [comment]
This should probably do it!?
```dokuwiki
<form>
action pagemod _self add_todo

fieldset "Add todo"

static "What shall be done?"
textbox  "todo_title"
</form>

===== Todos =====
Here is a list of the todos you'll add via the above form:
<pagemod add_todo output_before>  * <todo>##todo_title##</todo>
</pagemod>
```
Needs Bureaucracy and Pagemod-Plugin, of course.
