### ISSUE TITLE
feature request: uncheck all todos on a wiki page at once

### ISSUE THREAD

**Issue by ibot87** [leibler/dokuwiki-plugin-todo#127]
Hi,
thank you for the great plugin, it's been very helpful during the last years.

I would like to ask if it's possible to add somethink like an “uncheck button“ or an “uncheck all box“, so I could uncheck all todos on a single page at once.

Right now, for example when I go on vacation, I uncheck every single box one by one before I can check them again. Would be great :)

**Comment by einhirn** [comment]
I suggest using either a "bulk edit" plugin for dokuwiki or using "search and replace" while Editing the wiki page. I don't see that there'll be new features in this plugin any more - but of course a pull request is welcome.

**Comment by ibot87** [comment]
Thank you for your hints, I'll try one of these.

Unfortunately I don't have programming skills for such things, but maybe someone else is interested =)

**Comment by rtbhouse-joaoarruda** [comment]
upvoting this feature, it would be indeed awesome

**Comment by mark2016** [comment]
If you would like to reset all todo items on a page using a cronjob (that runs at a certain time or schedule) then you can use a sed command.  Here you need to find the full path to the Dokuwiki page, you can check this with your website file browser.  They usually live in "pages" directory, eg command
`$ sed -i 's/<todo #[^>]*>/<todo>/g' /home/user/public_html/data/pages/namespace/example_page.txt`

The regex here is searching for any `<todo #(anything except ">")>` and replacing it with a blank `<todo>`.  Could probably adjust it for due dates and so on but I use it for a daily reminder checklist, so very simple usage for my use case.

**Comment by einhirn** [comment]
This feature "uncheck all checkboxes" is available now, thanks to @RobertWeinmeister
