### ISSUE TITLE
Counting todos does not work (short list)

### ISSUE THREAD

**Issue by chaotic-bruno** [leibler/dokuwiki-plugin-todo#128]
Hey,

I just discovered that the short list is only rendered if there are no todo's for the person I'm trying to render or at all.
I think it's caused by the line "return $pages;" in the foreach loop - could someone please verify? 

https://github.com/leibler/dokuwiki-plugin-todo/blob/03fb911fb2b4c47b5a242422f1b993a57b61e67e/syntax/list.php#L362

**Comment by runout-at** [comment]
On Wed, 2020-09-23 at 09:11 -0700, chaotic-bruno wrote:
> I just discovered that the short list is only rendered if there are
> no todo's for the person I'm trying to render or at all.
> I think it's caused by the line "return $pages;" in the foreach loop
> - could someone please verify? 
> 
> https://github.com/leibler/dokuwiki-plugin-todo/blob/03fb911fb2b4c47b5a242422f1b993a57b61e67e/syntax/list.php#L362

thx for reporting.
I think this could be a bug from copy/paste code.
As the varaiable $pages is not used inside this function and a return
statement at this position does not make sense this line should be
removed.

can you prepare a pull request?

**Comment by chaotic-bruno** [comment]
I tested the fix on Release rc-2020-06-09 "Hogfather" RC3.

Everything is normal and the shortlist is getting rendered - so I created the pull request.
