### ISSUE TITLE
Most of Todo lists options returns nothing

### ISSUE THREAD

**Issue by chtiland** [leibler/dokuwiki-plugin-todo#131]
Hi,

Some options in lists doesn't work (empty page and wich cache cleaned and disabled).

* ```~~TODOLIST short:yes~~```
* ```~~TODOLIST assigned:yes~~```
* ```~~TODOLIST assigned:username~~```
* ```~~TODOLIST assigned:@@USER@@~~```

Updating or reinstalling plugin has no effect (as link on  Dokuwiki point to stable)
Using manual install from master branch only solve ```~~TODOLIST short:yes~~```.

So I think that's probably the same problem as in issue #128 

Thanks

**Comment by runout-at** [comment]
Does this still exist in the latest version? Can you confirm please.

#128 was a issue of a code change by the OP himself.
