### ISSUE TITLE
A page display gets corrupted if it uses plugin:include

### ISSUE THREAD

**Issue by wataradio** [leibler/dokuwiki-plugin-todo#135]
### Problem

If a page, 'parent', includes an another page, 'child', with [plugin:include](https://www.dokuwiki.org/plugin:include),

```
parent page

{{page>child}} 
```

and the child page has a `<todo>` tag,

```
child page

<todo>ToDo</todo>
```

then, the parent page is displayed as follows. Until here, this is an expected behavior.

![image](https://user-images.githubusercontent.com/297248/122785205-246b6700-d2ee-11eb-9a8c-a982bcbdaa29.png)

But if you click the ToDo checkbox on the parent page and refresh the parent page, then, the parent page display gets corrupted as follows.

![image](https://user-images.githubusercontent.com/297248/122788641-7f528d80-d2f1-11eb-8532-dcd11cf60490.png)

You can see the parent page has been rewritten unexpectedly as follows.

![image](https://user-images.githubusercontent.com/297248/122788766-a315d380-d2f1-11eb-9785-4587ef1aec18.png)

```
parent page

{{page #hwatanabe:2021-06-21>child}}
```

### Versions

dokuwiki version: Hogfather
todo plugin version: 2020-06-17
include plugin version: 2021-03-06

**Comment by runout-at** [comment]
I think this is how the include plugin works and don't know how to send the checkbox-click to the included page to change the code there.

**Comment by runout-at** [comment]
If you have an idea how to send the checkbox-click to the included page - I will reopen this issue.

**Comment by einhirn** [comment]
Same issue as #137. We won't be able to send the "checked" to the correct page, but we should fix the detection of `<todo ...>`-blocks.
