### ISSUE TITLE
feature request: send e-mail for new todos

### ISSUE THREAD

**Issue by arlt** [leibler/dokuwiki-plugin-todo#136]
I have not found a possiblity to configure e-mail notification for new todos.
Maybe a keyword mail:yes|no and a default option in the preferences would be nice.
Would you like to implement this feature?

**Comment by einhirn** [comment]
I guess you could just subscribe to page changes using dokuwiki core features... You'd get a diff when someone edits the page, so you'd also be notified when there's a new todo...

**Comment by runout-at** [comment]
@arlt does the answer from einhirn solve your needs - then I'd close this?

I think implementing email features is a bigger task.

**Comment by arlt** [comment]
@runout-at no, but this is not a real problem since working has changed for us. Thanks!
