### ISSUE TITLE
Checkbox misalingment where blank <todo> tags present

### ISSUE THREAD

**Issue by tyler-wright** [leibler/dokuwiki-plugin-todo#138]
Hi there, quick one on a bug I think I've discovered.

I use this plugin to make a quick shopping list as my Dokuwiki is essentially a replacement for the various notepads I used to sprawl everywhere, so I might have a list like so:

```
===== Vegetables  =====

  * <todo>Broccoli</todo>
  * <todo>Carrots</todo>
  * <todo></todo>

===== Aromatics/Condiments =====

  * <todo>Garlic</todo>
  * <todo>Ginger</todo>
```

Notice that there is a blank <todo> tag on the third bullet point under Vegetables. This displays as just a blank bullet on the wiki page (all expected behaviour so far).

When I then go to tick 'Ginger' as completed however, and then navigate away from the page, when I come back it has applied the completed status to 'Garlic' instead, misaligned by one task. It seems you can continue adding blank tags to your document and it will misalign where the task completes by the same number of blank tags present.

This seems to be a bug - the expected behaviour is for blank tags not to render, and not to affect the completion status of any other tags.

**Comment by runout-at** [comment]
I'll close this issue as resolved in PR #154
