### ISSUE TITLE
Klicking checkboxes brings no action after updating to Dokuwiki "Igor"

### ISSUE THREAD

**Issue by duineamh** [leibler/dokuwiki-plugin-todo#144]
I now noticed (after some time after I have updated to Igor) that clicking the todo-checkboxes does not do any action (task is not marked as done, or vice versa).

If definitely worked before, when still using the previous release.

If I look at the source code, it seems like the JavaScript for TodoList is not loaded at all.

Dokuwiki version: 2022-07-31a "Igor"
Todo Plugin version: 2022-08-10

**Comment by arlt** [comment]
Works here without any problem.

Dokuwiki version: 2022-07-31a "Igor"
Todo Plugin version: 2022-08-10
CentOS 7.9 / PHP 7.4.32
CentOS 7.9 / PHP 8.1.11

**Comment by runout-at** [comment]
Works on Debian bullseye and bookworm.

I'll close this - OP didn't respond anymore.
