### ISSUE TITLE
Checkbox bug; Like  Checkbox only "checks" once. or Checkmark does not persist

### ISSUE THREAD

**Issue by ErisonChen** [leibler/dokuwiki-plugin-todo#151]
I have a problem similar to #85 and #92; when the todo Checkmark is clicked, it shows success and disappears when the page is refreshed. 

The problem also occurs when todo's Checkmark that have been checked before,  when i clicked it to uncheck, it will also be checked after refresh the webpage . 

I have used edittable to put various todo's into the table, when a cell has more than one todo, clicking on the bottom one will affect the display of the top one.

For example, the top one has checked, the bottom one has not yet checked, when clicking on the bottom one, the top one will become `<todo # # second # third> XXX </todo>`, so the bottom one is still not unchecked after refreshing.

For example, if both todo's above and below have not been checked, when clicking on the checkMark for the lower todo, the upper todo will be marked as done

When the two todo's are taken out of the table and put on the page next to each other, the above problem still occurs.

So I tested if there was a problem when there was only one todo in a cell from the table; the result is almost same, because there are no other todo's above it, it does not affect the others, but the status itself is still restored after refresh.

I probably have dozens of <todo> </todo> on this page, and I'd like to use this page to make a todo schedule, because there are too many todo's.

dokuwiki verison: Release 2022-07-31a "Igor"
todo   version: 2022-08-10

**Comment by ErisonChen** [comment]
This is exactly the same as #138 , and after checking as she described, there was indeed an empty `<todo></todo>`, and after deleting this, all previous actions worked.

**Comment by einhirn** [comment]
Please some Dokuwiki code for a sample page, so we can try to reproduce it. Use three Backticks (`) on their own line to start and end a code block... (Or just mark the text and click the `<>`-Button above to make it a code block 😁)

**Comment by runout-at** [comment]
I'll close this issue as resolved in PR #154
