### ISSUE TITLE
PHP8.2 Errors

### ISSUE THREAD

**Issue by runout-at** [leibler/dokuwiki-plugin-todo#155]
I open this issue for _all_ PHP8.2 related problems. (Personally, I test on Debian Bookworm with latest upgrades). Related branch: https://github.com/leibler/dokuwiki-plugin-todo/blob/php8.2

If you find something related, please refer to the appropriate sections here:

### Undefined array key

> Undefined array key "todousers" in /home/dw01/dokuwiki/lib/plugins/todo/syntax/list.php on line 425

https://github.com/leibler/dokuwiki-plugin-todo/blob/4f36f53781bbdb074262766d94d2404836f3e16d/syntax/list.php#L425C8-L425C89

Maybe this could be fixed with  `array_key_exists(string|int $key, array $array): bool` which seems to work:

`if (!$condition2 && is_array($data['assigned']) &&  array_key_exists('todousers', $data)  && is_array($data['todousers']))`

- Would we still need the `is_array($data['todousers'])` check?
- Is this necessary for `$data['assigned']` too?
- Shall we rewrite all `is_array` checks (list.php: 418, 425, 431; todo.php: 421)?
- Maybe it would be sufficient to check with `isset()`?

**Comment by Autumnf0x** [comment]
I have the same E_WARNING's in DokuWiki log, and this:
```
E_WARNING: Trying to access array offset on value of type bool/var/www/dokuwiki/lib/plugins/todo/syntax/todo.php(331)
    #0 /var/www/dokuwiki/lib/plugins/todo/syntax/todo.php(331): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/dokuwiki/lib/plugins/todo/syntax/todo.php(256): syntax_plugin_todo_todo->_prepUsername()
    #2 /var/www/dokuwiki/lib/plugins/todo/syntax/todo.php(162): syntax_plugin_todo_todo->createTodoItem()
    #3 /var/www/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_todo_todo->render()
    #4 /var/www/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
    #5 /var/www/dokuwiki/inc/parserutils.php(158): p_render()
    #6 /var/www/dokuwiki/inc/parserutils.php(96): p_cached_output()
    #7 /var/www/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
    #8 /var/www/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #9 /var/www/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #10 [internal function]: tpl_content_core()
    #11 /var/www/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
    #12 /var/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #13 /var/www/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #14 /var/www/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
    #15 /var/www/dokuwiki/inc/actions.php(27): include('...')
    #16 /var/www/dokuwiki/doku.php(126): act_dispatch()
    #17 {main}
```
> Dokuwiki Release 2023-04-04a "Jack Jackrum";
> PHP 8.2;
> StepByStep Plugin last updated on 2023-07-27;
> ToDo Plugin version: 2023-07-14
> Last updated: Sat, 29 Jul 2023 06:20:01 by Extension Manager.

**Comment by runout-at** [comment]
@Autumnf0x thanks for reporting this!

Please, could you provide the DW-Code of the todo and/or list definition which triggers this. I'm not sure if this is really a PHP 8.2 related error or maybe a bug in the code.

**Comment by Autumnf0x** [comment]
So, I finally studied the case in more detail.
I found the following bug:

* There is a page on which there is a plugin syntax, like:
`<todo @admin @developer>Page in developing.</todo>`
* When I mark this ToDo as completed, it is displayed on the page accordingly, and the code for this ToDo becomes this:
`<todo @admin @developer #mysecretusername:2023-07-31>Page in developing.</todo>`

Seems to it's all right.

Here is the obvious error:

* There is a page on which "TODOLIST" is placed.
* The page I was talking about earlier is in the namespace specified in the given "TODOLIST":
`~~TODOLIST ns:mynamespace:firstheader~~`
* Accordingly, this page is displayed in this "TODOLIS" - it's ok.

**But:**

* Case 1: If, on the ToDo page, there is a mark "done", then:
  * The item "TODOLIST" related to this page will not change and will still be displayed as "not done";
  * If, in such case, I try to mark a ToDo on TODOLIST as "done", I get the message: *"A newer version of this page is available. Refresh the page before trying again."* And nothing else will change - refreshign page constantly shows the item (and all others) as "not done";
* Case 2: If the ToDo on page is NOT marked as "done", then:
  * Try to mark ToDo on TODOLIST as "done": it will be marked as done and on target page related ToDo will be marked as well;
  * **BUT:** But after updating (reloading) the page with TODOLIST - all ToDos are unchecked again (At the same time, ToDo's are marked as completed on the related pages).
	
And the number of logs I show in the last post - corresponds to the number of ToDo tags in the Wiki marked as "done".


> *And the value from the settings for displaying the username*
- It seems I do not really understand what exactly in what settings and where I should look at... :(

> There might be no proper definition of a default value for` $data['username']` and if you do not use exactly the specified keywords it could trigger this bug:
- And here .. - even more unclear (...

What exactly and where exactly should I check?

**Comment by runout-at** [comment]
@Autumnf0x :

Could you try to change the code to:
https://github.com/leibler/dokuwiki-plugin-todo/blob/603b03257c136774c94dc4ee5e330efdc27c19de/syntax/todo.php#L201-L208

And regarding the settings:
The value from  the `Admin-Page` in `Configuration Settings `: `Plugins | Todo | plugin»todo»Username`

**Comment by Autumnf0x** [comment]
> And regarding the settings:
> The value from the `Admin-Page` in `Configuration Settings `: `Plugins | Todo | plugin»todo»Username`

-- the value is 'real'.

> Could you try to change the code to: ...

Sure. Replace with given code, and...
...Disappear only
> * I get the message: _"A newer version of this page is available. Refresh the page before trying again."_

from case in my previous post. No more effects. Everything else remains the same.

**Comment by Autumnf0x** [comment]
> > And regarding the settings:
> > The value from the `Admin-Page` in `Configuration Settings `: `Plugins | Todo | plugin»todo»Username`
> 
> -- Thanks for the explanation - the value is 'real'.
> 
> > Could you try to change the code to: ...
> 
> Sure. Replace with given code, and... ...Disappear only
> 
> > * I get the message: _"A newer version of this page is available. Refresh the page before trying again."_
> 
> from case in my previous post. No more effects. Everything else remains the same.

Still doesn't work.

**Comment by ajshea** [comment]
> * There is a page on which "TODOLIST" is placed.

Is there also a `~~NOCACHE~~` on the page?

**Comment by Autumnf0x** [comment]
> > * There is a page on which "TODOLIST" is placed.
> 
> Is there also a `~~NOCACHE~~` on the page?

Shame on my gray beard!
I've been using it for so long that I forgot about this feature. It works now.
Thank you. :)
