### ISSUE TITLE
WARNING: Undefined array

### ISSUE THREAD

**Issue by herkul-s** [leibler/dokuwiki-plugin-todo#169]
Windows10 Pro 64bit
DokuWikiStick Release 2024-02-06a "Kaos"
ToDo Plugin 2024-02-01

**2024-03-02 19:08:16 E_WARNING: Undefined array key 1**
**E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161)**
```
#0 E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161): dokuwiki\ErrorHandler::errorHandler()
#1 E:\DokuWikiStick\dokuwiki\inc\parser\renderer.php(126): syntax_plugin_todo_todo->render()
#2 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(535): Doku_Renderer->plugin()
#3 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(299): p_render_metadata()
#4 E:\DokuWikiStick\dokuwiki\inc\common.php(262): p_get_metadata()
#5 E:\DokuWikiStick\dokuwiki\doku.php(101): pageinfo()
#6 {main}
```
    
**2024-03-02 19:08:16E_WARNING: Undefined array key 1**
**E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161)**
```
#0 E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161): dokuwiki\ErrorHandler::errorHandler()
#1 E:\DokuWikiStick\dokuwiki\inc\parser\renderer.php(126): syntax_plugin_todo_todo->render()
#2 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(691): Doku_Renderer->plugin()
#3 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(158): p_render()
#4 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(97): p_cached_output()
#5 E:\DokuWikiStick\dokuwiki\inc\template.php(1658): p_wiki_xhtml()
#6 E:\DokuWikiStick\dokuwiki\lib\tpl\dokuwiki\main.php(44): tpl_include_page()
#7 E:\DokuWikiStick\dokuwiki\inc\actions.php(30): include('...')
#8 E:\DokuWikiStick\dokuwiki\doku.php(131): act_dispatch()
#9 {main}
```    
**2024-03-02 19:08:16E_WARNING: Undefined array key 1**
**E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161)**
```
#0 E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161): dokuwiki\ErrorHandler::errorHandler()
#1 E:\DokuWikiStick\dokuwiki\inc\parser\renderer.php(126): syntax_plugin_todo_todo->render()
#2 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(691): Doku_Renderer->plugin()
#3 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(158): p_render()
#4 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(97): p_cached_output()
#5 E:\DokuWikiStick\dokuwiki\inc\Ui\PageView.php(67): p_wiki_xhtml()
#6 E:\DokuWikiStick\dokuwiki\inc\Action\Show.php(40): dokuwiki\Ui\PageView->show()
#7 E:\DokuWikiStick\dokuwiki\inc\template.php(120): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core()
#9 E:\DokuWikiStick\dokuwiki\inc\Extension\Event.php(134): call_user_func_array()
#10 E:\DokuWikiStick\dokuwiki\inc\Extension\Event.php(200): dokuwiki\Extension\Event->trigger()
#11 E:\DokuWikiStick\dokuwiki\inc\template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#12 E:\DokuWikiStick\dokuwiki\lib\tpl\dokuwiki\main.php(60): tpl_content()
#13 E:\DokuWikiStick\dokuwiki\inc\actions.php(30): include('...')
#14 E:\DokuWikiStick\dokuwiki\doku.php(131): act_dispatch()
#15 {main}
```    
**2024-03-02 19:08:16E_WARNING: Undefined array key 1**
**E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161)**
```
#0 E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161): dokuwiki\ErrorHandler::errorHandler()
#1 E:\DokuWikiStick\dokuwiki\inc\parser\renderer.php(126): syntax_plugin_todo_todo->render()
#2 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(535): Doku_Renderer->plugin()
#3 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(299): p_render_metadata()
#4 E:\DokuWikiStick\dokuwiki\inc\indexer.php(154): p_get_metadata()
#5 E:\DokuWikiStick\dokuwiki\inc\TaskRunner.php(206): idx_addPage()
#6 E:\DokuWikiStick\dokuwiki\inc\TaskRunner.php(52): dokuwiki\TaskRunner->runIndexer()
#7 E:\DokuWikiStick\dokuwiki\lib\exe\taskrunner.php(20): dokuwiki\TaskRunner->run()
#8 {main}
```    
**2024-03-02 19:08:20E_WARNING: Undefined array key 1**
**E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161)**
```
#0 E:\DokuWikiStick\dokuwiki\lib\plugins\todo\syntax\todo.php(161): dokuwiki\ErrorHandler::errorHandler()
#1 E:\DokuWikiStick\dokuwiki\inc\parser\renderer.php(126): syntax_plugin_todo_todo->render()
#2 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(535): Doku_Renderer->plugin()
#3 E:\DokuWikiStick\dokuwiki\inc\parserutils.php(299): p_render_metadata()
#4 E:\DokuWikiStick\dokuwiki\inc\common.php(262): p_get_metadata()
#5 E:\DokuWikiStick\dokuwiki\doku.php(101): pageinfo()
#6 {main}
```

**Comment by runout-at** [comment]
todo.php(161) should not be reached as there is a [check if the array is empty](https://github.com/leibler/dokuwiki-plugin-todo/blob/d18f42bc8eec8560551d83bfa6c4212d8b84bcf3/syntax/todo.php#L157-L161)

I'm not aware of a change in php empty() function.

As you run windows please make sure this is not a platform related problem.

Can you please provide the DW code which triggers the issue.

**Comment by herkul-s** [comment]
What I did:
- I downloaded DokuWikiStick (contains MicroApache with PHP)
- unzipped the downloaded file into a folder
- I started DokuWiki and made the initial settings
- I downloaded the ToDo plugin in dokuwiki
- in edit mode I typed `<todo>test</todo>`
- an error occurred after saving the page

**Comment by runout-at** [comment]
I's _only_ a warning. You can ignore that for now. You might see _array key_ warnings for other plugins too.

We'll try to fix it for the todo plugin in the next release.

Normally the warnings should go only to the logs. Maybe you have the debug mode enabled in Admin->Settings if you see them i the browser.

**Comment by runout-at** [comment]
We do things like this: `array_merge(array($state, 'match' => $match))` in several places.

I don't know if the first parameter _$state_ for sure gets an index/key of _0_. in L157 `if(empty($data))` does not trigger in as the array is not empty but in L161 the ` $state = $data[0]` will not find the key _0_.

I'm confused as the log says 'Undefined array key 1' - why _1_ if the code says key _0_?

Anyone with ideas how to solve this properly?

**Comment by einhirn** [comment]
This issue is confused by looking at code that was changed after the release used. In the release 2024-02-01 line 161 still says

```
        [$state, $match] = $data;
```

which I just now learned could be fixed with

```
        [$state, $match] = array_pad($data,2,null);
```
or something. But since we already have a different fix for that, I'll just take a look at what else will need to be merged and create a new release.

**Comment by einhirn** [comment]
New release is out, just update the plugin, error should be gone.
