### ISSUE TITLE
CKGEdit Plugin integration

### ISSUE THREAD

**Issue by bastiiiii** [leibler/dokuwiki-plugin-todo#170]
Hi,

any solution for an integration of the [CKGEdit Plugin](https://www.dokuwiki.org/plugin:ckgedit)?

Thanks!

**Comment by einhirn** [comment]
From ckgedit plugin docs:

> #### Plugin Handling
> You enter plugin markup directly into the CKEditor window, just as do in the native Dokuwiki editing window. When the document is saved, the plugin's graphics, if there are any, will display in the browser. When you reload the page into the CKEDitor, the markup is again displayed. So,if you were using the wrap plugin, this is what you might see in the CKEditor:
> ```
> <WRAP centeralign>
> Center aligned text ...
> </WRAP>
> ```
> But in the browser, the text would be displayed as centered. See a more complete example [here](http://www.mturner.org/devel/doku.php?id=playground:ckgedit_wrap).

As for integration: That would be an extension of the ckgedit plugin and not related to this plugin.
