### ISSUE TITLE
option to not stamp user/date when it is checked 

### ISSUE THREAD

**Issue by dwightmulcahy** [leibler/dokuwiki-plugin-todo#176]
When you check off a TODO, it is marked with the user name and date it was checked.

<img width="705" alt="image" src="https://github.com/user-attachments/assets/4a76be27-adc6-404b-bf1c-4687c1692f02">

I want an option that does not stamp it when it is marked.

Something like this?
```
<todo nostamp></todo><todo nostamp></todo><todo nostamp></todo><todo nostamp></todo><todo>Drink Glass of Water</todo>
```

So that when you check it off it will look like this:
<img width="329" alt="image" src="https://github.com/user-attachments/assets/de570ecf-545f-4497-82d6-726eaa939b87">

```
<todo nostamp #dwight:2024-08-28></todo><todo nostamp #dwight:2024-08-28></todo><todo nostamp #dwight:2024-08-28></todo><todo nostamp></todo><todo nostamp></todo><todo nostamp></todo><todo nostamp>Drink Glass of Water</todo>
```

<img width="326" alt="image" src="https://github.com/user-attachments/assets/ec208b30-acff-4bf8-860e-45f4d2d50a29">

**Comment by dwightmulcahy** [comment]
Ugh, Ok found under `Render username` in the docs that there is `username:none`.

```
<todo username:none #dwight:2024-08-28></todo><todo username:none #dwight:2024-08-28></todo><todo username:none #dwight:2024-08-28></todo><todo username:none></todo><todo username:none></todo><todo username:none></todo><todo username:none>Drink Glass of Water</todo>
```

Renders the way I want like this:
<img width="331" alt="image" src="https://github.com/user-attachments/assets/c90cc7cd-3b5d-4577-89e6-15fc15f85093">


SUGGESTION: Expand the `Render username` section with examples of each and how they display.

**Comment by einhirn** [comment]
> SUGGESTION: Expand the `Render username` section with examples of each and how they display.

Thanks for your offer - go ahead and update the documentation as needed. 😉

**Comment by runout-at** [comment]
thx!
