### ISSUE TITLE
Regarding TODOList View

### ISSUE THREAD

**Issue by rishikachhawaha** [leibler/dokuwiki-plugin-todo#29]
Hi,
I want you to add two type of TODOList View
1. The Simple view which just contains the TODO task along with the due date and status. (This is the current TODOList in the latest version)
2. I want you to make a broad view of TODOList which contains :-
TASK | ASSIGNED TO | STATUS | CREATED BY | COMPLETION MESSAGE(With Completion Date)
like this columns, so that we can review each and every task.

Thank you :)

**Comment by einhirn** [comment]
Feel free to send a pull request.
