### ISSUE TITLE
Problem with marking tasks complete after upgrade

### ISSUE THREAD

**Issue by dayb1** [leibler/dokuwiki-plugin-todo#31]
I recently upgraded the dokuwiki todo plugin to the latest release.
Since them I am unable to mark a task as completed by ticking the tick box on the task. The setting is "forgotten" on returning to the page.
This happens when either ticking the summarized todo list or the todo action on the individual page.
Any assistance would be gratefully received. Thank you.

**Comment by runout-at** [comment]
I close this because there were no comments for a long time.
If this issue hits you, please reopen it.
