### ISSUE TITLE
Request: Show Who Completed Task

### ISSUE THREAD

**Issue by majorsl** [leibler/dokuwiki-plugin-todo#35]
Apologies if this is a feature, I may have overlooked it in the docs.

I have a simple, yet lengthy, to-do list where multiple users could complete actions in it. It does not need to be assigned to anyone in particular.  I'd like to know, in the list, who the user was that checked off the list.  It might look like:

-Task1- -completed by John Doe
Task2
-Task3- -completed by Jane Doe

Again, maybe this exists and I'm not sure how to format the list to do so.

**Comment by Braintelligence** [comment]
I'd also like to know where this information is viewable now.

**Comment by runout-at** [comment]
at the moment only in the pages source.

**Comment by Braintelligence** [comment]
So I need to look at who edited the "#" in there?

**Comment by runout-at** [comment]
see comment above: commented on Oct 30, 2014
i know - its not yet the perfect solution.

**Comment by einhirn** [comment]
Added patch to display output. If that's not wanted, you'll need to use "user:none" syntax to prevent display. Maybe a bit crude, but works for now. https://github.com/leibler/dokuwiki-plugin-todo/commit/60db5b5d600af23c8dbcf11364ec4919b6cd957e
