### ISSUE TITLE
Request: Show all assigned usernames

### ISSUE THREAD

**Issue by matzekuh** [leibler/dokuwiki-plugin-todo#43]
Hello,

if there are several users assigned to one task only the first username is viewed between the brackets. Could you consider offering an option to show all users assigned to a task?

Thank you for your great work.

Kind regards,
matzekuh

**Comment by real-or-random** [comment]
I'm interested in this feature as well, and I can prepare a pull request.

I guess an option that allows to select a number of shown users (or infinity) would be best. What do you think?

**Comment by runout-at** [comment]
for me ok.
you could make the default value configurable in 'settings'.

**Comment by einhirn** [comment]
Stale feature request, will close.
