### ISSUE TITLE
Links inside a <todo> does not work

### ISSUE THREAD

**Issue by ParoTheParrot** [leibler/dokuwiki-plugin-todo#47]
Example:
`<todo> https://www.dokuwiki.org/plugin:todo</todo>`

**Comment by marcocevoli** [comment]
Same here. It happens both for links internal to the wiki and for external links.

**Comment by polyzen** [comment]
I just resort to putting them directly after the todo:
`<todo>Learn crossfit</todo> [[user:dan:fitness:Crossfit]]`

**Comment by smaug9** [comment]
I think links are considered formatting, which doesn't work within <todo> tags. LIke polyzen, I add the link outside/after of the <todo> tags.

**Comment by Megachip** [comment]
Would be nice to have support for that

**Comment by louwers** [comment]
@einhirn Could you open this as an enhancement request?
