### ISSUE TITLE
todo date problem

### ISSUE THREAD

**Issue by stegzzz** [leibler/dokuwiki-plugin-todo#48]
Hi, I write:

`<todo due:2015-03-15>⇑end of year finance</todo>`

in one of my DokuWiki (Release 2014-09-29c "Hrun") pages and it produces the following error:

Warning: DateTime::format() [datetime.format]: The DateTime object has not been correctly initialized by its constructor in mydirectory/dw/lib/plugins/todo/syntax/todo.php on line 343
 [ → ]⇑end of year finance

todo installed version 2014-11-26

Please can you tell me what I'm doing wrong? Thanks, stegzzz

**Comment by runout-at** [comment]
which version of php do you use on your server?
what ist the standard date format on the server?

**Comment by stegzzz** [comment]
The server is running php 5.2.17

Not sure how to establish server date format. Any suggestion?

**Comment by runout-at** [comment]
You should upgrade to php 5.4

**Comment by stegzzz** [comment]
Thanks, that worked!
