### ISSUE TITLE
exclude specific namespaces from todolist

### ISSUE THREAD

**Issue by orzechow** [leibler/dokuwiki-plugin-todo#49]
I have a dokuwiki page printing all my unassigned & uncompleted todos using

```
~~TODOLIST assigned:no completed:no~~ 
```

which works well.

But I have a namespace `playground` (as the name says, just a wiki playground) which I'd like to exclude from that list.
As far as I understand there is no such possibility for `TODOLIST` yet.

So a feature to exclude namespaces from the `TODOLIST` would be nice! Syntax might be something like

```
~~TODOLIST ns:\playground~~
```

**Comment by Braintelligence** [comment]
#50 related
:+1: +1

**Comment by runout-at** [comment]
i was thinking about that when i cleaned up the code last time but didn't see a real usecase but this is a good example.
i would prefere a slightly different syntax: ns:!playground for example.

Its relatively easy to exclude just one namespace.
The bettter solution would be to have the option to
  * define multiple namespaces inside the todo tag like ns:included1,included2,!exluded1,!excluded2,...
  * define excluded namespaces in a central configuration

**Comment by orzechow** [comment]
Well I'm open to any syntax as long as it's easy and clean ;)
Looking forward to an implementation of this feature!

Additionally to your options, you might consider a macro like

    ~~NOTODOLIST~~

to opt-out specific pages from todo crawling.
That's not directly related to this issue, but also a way of excluding pages from todolists, that some users might find useful.

**Comment by runout-at** [comment]
~~NOTODO~~
i have included a line of code to skip pages from parsing for todo tags when this macro is found.
please check if this works for you as expected.

just i don't know how to hide this text on the page.

**Comment by Braintelligence** [comment]
As a quick solution this is nice for template pages! 
Such syntax would be perfect for the future: ns:included1,included2,!exluded1,!excluded2,

**Comment by runout-at** [comment]
true.
it was just very easy but not very useful bechause what is the reason to define todos on a page and then exlude it from _all_ todolists?

**Comment by Braintelligence** [comment]
It's useful for templates. You just need to instruct the users to remove that part after creating the page itself.
I have to do this for another reason right now, anyway.

**Comment by runout-at** [comment]
i just did a check for template files.
they do _ not_ get parsed anyways (don't know why).

**Comment by Braintelligence** [comment]
They do for me.
My template pages are named "seitenvorlage", maybe this is only true for the standard template name?

**Comment by runout-at** [comment]
i think, this is why templates should start with an underscore '_'
maybe you will run into other issues as well.

**Comment by Braintelligence** [comment]
I'm pretty sure the old template page name was "template" without an underscore o_o...
Do you use underscore for template page names? I wasn't aware of that.
I'm using a bunch of plugins and never had a problem up till now.

**Comment by orzechow** [comment]
@runout-at is right, templates start with an underscore or even two (if you want them to be also for subnamespaces)
Check out the [manual](https://www.dokuwiki.org/namespace_templates) ;)
There are also some plugins extending the default template mechanism (one template only for the whole namespace), if needed.

**Comment by Braintelligence** [comment]
Mea maxima culpa.
I always use the template pagename plugin with dokuwiki installs so I can edit them within dokuwiki by giving them a standard name.
(As recommended in the manual if you want to be able to edit them within dokuwiki.)

And I don't think I'm the only one who needs this functionality. That's why you shouldn't rely on underscores I think.

**Comment by orzechow** [comment]
Okay right, if you change the template names in order to edit them within the dokuwiki frontend, other plugins treat them as normal articles of course.
