### ISSUE TITLE
Create todo pages (allowlinks) in specific namespaces

### ISSUE THREAD

**Issue by Braintelligence** [leibler/dokuwiki-plugin-todo#51]
Hi there,

it would be nice if you could specify tags or something like that so todo pages would be created in specific different namespaces.

Use-case:
I have several root namespaces with different security levels, related to the user group of a user. Showing only the todos of the allowed security levels worked right out of the box but if you create a todo page by clicking on the link you can only specify ONE namespace where todo pages are created.

My workaround right now is to relink such created sites to manually created todo pages in security restricted namespaces. This is cumbersome, though, because not many people have the right to do so within the wiki.

<todo pagespace:hi-sec>If you click this task, the todopage will be created within the hi-sec namespace and/or you will be transfered there</todo>

Something like this would be perfect.

**Comment by orzechow** [comment]
Well you can set a relative namespace for your todo pages, wouldn't that help?

    plugin»todo»ActionNamespace: .:todos

This setting would create todo pages of a todo in `hi-sec:mypage` page in the `hi-sec:todos` namespace, while those todos in `low-sec:mypage` page would be created in `low-sec:todos`

**Comment by Braintelligence** [comment]
Is it also possible to set different absolute namespaces? I don't want to spam all my namespaces with todo-pages, only four specific of those.

**Comment by Braintelligence** [comment]
For example I would like to have four namespaces for todos:

special-sec:tasks:...
hi-sec:tasks:...
middle-sec:tasks:...
no-sec:tasks:...

How would I go about creating the todos within those namespaces as long as their first level root folder is the related security level folder?

**Comment by einhirn** [comment]
So from what I gather, we'd need to limit the "relative namespace" notation to 1st level or something. Or allow alternatives in "action namespace" that are selected by best match... Not sure which would be better/have a broader user base. Or which would be easier to implement. Currently there is nothing fancy going on - the configured action name space is just prepended to the page name, that's it.

Take a look at the code and send a pull request if you've got a suggestion.
