### ISSUE TITLE
Look for tasks within discussion metafiles

### ISSUE THREAD

**Issue by Braintelligence** [leibler/dokuwiki-plugin-todo#52]
Hi there,

I'm using this plugin:

https://www.dokuwiki.org/plugin:discussion

You can allow wiki syntax within the plugin which also allows TODO syntax. They don't appear within ~~TODOLIST~~ though so I guess the todo plugin doesn't search through the correlating metafiles.

Would it be possible to implement this? Until then I can't allow the wiki syntax within the comments =/

**Comment by einhirn** [comment]
I don't see how we can do anything about that - "discussion" plugin calls "render_text" to render wiki syntax in comment section. I can't say why that doesn't trigger the hooks we add to the renderer.
