### ISSUE TITLE
Javascript "ReferenceError: todo is not defined" with version 2015-03-15

### ISSUE THREAD

**Issue by hh-lohmann** [leibler/dokuwiki-plugin-todo#58]
Updating to version 2015-03-15 made checkboxes dysfunctional, i.e. nothing happens on clicking them, Firefox' Web / Browser Console states "ReferenceError: todo is not defined", downgrading to todo plugin version 2014-11-26 brings functionality back

**Comment by runout-at** [comment]
My installation with the latest version 2015-03-15 works as expectet. no problems.
