### ISSUE TITLE
Bug - "<todo>task</todo>>" breaks page completely

### ISSUE THREAD

**Issue by issmirnov** [leibler/dokuwiki-plugin-todo#59]
Problem:
- With the todo plugin enabled, entering `<todo>task</todo>>"` and then saving the page breaks any content following it. The sidebar actions such as view past revisions and edit page are also nuked, so the only way to restore is to append `?do=edit` to the URL by hand.

Steps to reproduce:
1. Open a new page, I suggest the playground
2. Enter the following text:
```
some text
<todo>task</todo>>
more text here
```
3. Save the page.

Result:
![todo-bug](https://cloud.githubusercontent.com/assets/5771615/7426338/b71e2f26-ef77-11e4-9429-27de9d8474eb.png)

Plugins in use on my wiki: http://smirnov.wiki/wiki/info

My guess is this may be a conflict with the Markdown plugin, but if not then it's likely an issue with this code.

**Comment by orzechow** [comment]
Maybe you're right with the Markdown plugin - I don't use it and have no troubles:

![image](https://cloud.githubusercontent.com/assets/5220714/7429150/bd3ca6b4-effc-11e4-8bf1-1711881cf87a.jpg)

Comparing all the other plugins would be too much effort.
Why don't you try to deactivate the markdown plugin for a short while to test for the bug?

**Comment by issmirnov** [comment]
Confirmed. Disabled the markdown and it renders same as yours. 

Do you think this is worth fixing? It's not a terrible inconvenience as long as people know the url trick.

**Comment by orzechow** [comment]
Is there a specific reason / use case you use a `>` character after the closing todo tag?
Seems to be a rather unlikely case to me.

Don't know if it's worth to fix it. I'm not really familiar with the code.

**Comment by issmirnov** [comment]
Not at all, the only reason I brought it up is since it breaks the sidebar,
so some people may not know how to undo this.
