### ISSUE TITLE
Problem with start: and due:

### ISSUE THREAD

**Issue by Vi4Ever** [leibler/dokuwiki-plugin-todo#63]
Got a problem when using the start: and due: tags in a todo entry.
No page is returned at all when putting the start: or due: attribute in the todo tag.
Context (dokuwiki hrun), version 2014-11-26 
Leaving them out of the todo's.

**Comment by runout-at** [comment]
maybe a bug in an old version.
feel free to reopen this issue if you still have the problem with the latest version.
