### ISSUE TITLE
todolist to show checked/completed dates.

### ISSUE THREAD

**Issue by pmgeuze** [leibler/dokuwiki-plugin-todo#64]
Is it possible to show the completed date in the ~~todolist~~? I see that I can filter by start and due, but I would like a list of completed tasks and when they were done by date and if possible by hh:mm.

I am using the checklists to create case notes on forensic computer analysis. By checking the todo list items that I do, and using the ~~todolist~~ I create a master lists of all the completed tasks that I did in a case. I would like to then be able to show which tasks were 'checked' on which date.

Thank you for your efforts.

**Comment by einhirn** [comment]
Done: see #35 - except for HH:MM - that would need another patch...
