### ISSUE TITLE
Color print

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [leibler/dokuwiki-plugin-todo#69]
Hi,

the formatting of todo entries after reaching the start or due time is very helpful. Nevertheless this feature isn't supported when printing a page. So my question is if there is a possibility to turn on a color print for todo lists.

Best regards
Juergen

**Comment by runout-at** [comment]
Maybe this is because normally you don't want to print background colors.
Right now i don't know how to tell the printer to print the background color just for a task definition.

**Comment by runout-at** [comment]
This even does not work with PDF-export (pdf-plugin) PDF-printing (CUPS) nor with the print preview of firefox.
