### ISSUE TITLE
Declarations of handle and renderer in syntax_plugin_todo_todo not compatible with those of Dokuwiki_Syntax_Plugin

### ISSUE THREAD

**Issue by polyzen** [leibler/dokuwiki-plugin-todo#72]
PHP Warning:  Declaration of syntax_plugin_todo_todo::handle($match, $state, $pos, Doku_Handler &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos,
 Doku_Handler $handler) in /var/lib/dokuwiki/plugins/todo/syntax/todo.php on line 506
 PHP Warning:  Declaration of syntax_plugin_todo_todo::render($mode, Doku_Renderer &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $ren
derer, $data) in /var/lib/dokuwiki/plugins/todo/syntax/todo.php on line 506

**Comment by runout-at** [comment]
see #73
