### ISSUE TITLE
Add tags/categories to todo items to create filtered TODOLISTs

### ISSUE THREAD

**Issue by Semmu** [leibler/dokuwiki-plugin-todo#75]
Hi!

Is there a way to categorize/tag todo items? This feature would be really helpful to create separate tables for each type.
A workaround is to assign non-existing users as some kind of tags, but it makes the unassigned table pointless, since every item will have an assignee.

**Comment by piftouf** [comment]
Hi all. I agree with Semmu, Categorize todo would be really helpfull.

**Comment by einhirn** [comment]
See #97 - maybe @pavel-g will send a pull request and we can work off of that?
