### ISSUE TITLE
Access Keys Do Not Work

### ISSUE THREAD

**Issue by mdeabreu** [leibler/dokuwiki-plugin-todo#76]
In edit mode, using the keyboard shortcut [T] does not work as expected; instead of inserting a new ToDo item the shortcut jumps me to the top of the page and appending `#dokuwiki__top` to my URL.

According to https://www.dokuwiki.org/accesskeys the [T] accesskey moves to the top of the page and this accesskey seems to take precedence over the one assigned in the ToDo plugin.

**Additional information**
Chrome 49.0.2623.112m on Windows 10 x64 (also tried on Windows 7, same results)
ToDo version 2015-03-15
DokuWiki version "Detritus" (2015-08-10)

**Comment by runout-at** [comment]
i would suggest to remove the shortcut. or at least make it a hidden feature.

**Comment by runout-at** [comment]
I removed the shortcut key in 'master'.
