### ISSUE TITLE
wrong item checked/changes not saved between page reloads

### ISSUE THREAD

**Issue by 400thecat** [leibler/dokuwiki-plugin-todo#83]
when I have multiple todo items on a page and check the check-box on one of them, sometimes following problems occur

a) the item looks "checked" but when I reload the page another item is "checked" instead

b) the check-box is checked at the correct item, but another item's text is crossed off

c) correct item is checked, but when I "uncheck" and reload the page, it is checked again

Does anybody else experience these problems?
Any idea how to fix this?

**Comment by runout-at** [comment]
can you provide more details?
code examples?
version of DW and TODO plugin?

**Comment by 400thecat** [comment]
dokuwiki: Release 2015-08-10a "Detritus" 
todo plugin: date   2015-03-15

Basically, the problem is:
I load a page with several todo items. one of them is checked. I uncheck the item, reload the page, and it is checked again (changes were not saved). There is no example that reliably reproduces this problem. Sometimes this happens, sometimes same code works OK.

I will be happy to provide more details.

I appreciate you are investigating this issue

**Comment by runout-at** [comment]
can you please update to the latest versions.

**Comment by 400thecat** [comment]
The plugin itself is latest version AFAICT. 
Or did you mean updating whole dokuwiki ? I cannot do that. I have couple of custom plugins, which would need to be migrated first.

**Comment by runout-at** [comment]
i just merged some enhancements from master to stable. but that should not be associated to your problem.

Yes i mean the whole wiki.
Or try an old version of the plugin if you can not upgrade.

and did you see the discussion #31 - can you confirm this is the same issue?

**Comment by runout-at** [comment]
Which OS and Webserver do you use?

**Comment by runout-at** [comment]
No comments since 6 month. So i close it.
