### ISSUE TITLE
TODOLIST with several TODOs in one line

### ISSUE THREAD

**Issue by aruehl** [leibler/dokuwiki-plugin-todo#84]
Conacting several todos in one line, for example in a table structure, will not be splitted in different tasks:

&lt;todo&gt;one&lt;/todo&gt; \\\\ &lt;todo&gt;two&lt;/todo&gt;
is shows as:
 one&lt;/todo&gt; \\\\ &lt;todo&gt;two
and not as:
 one
 two

**Comment by aruehl** [comment]
And know use ~~TODOLIST ~~

**Comment by runout-at** [comment]
i don't understand what you mean.

**Comment by aruehl** [comment]
![todolist](https://cloud.githubusercontent.com/assets/3062585/21794561/afd0bf3c-d6fb-11e6-9c72-6da9919e3244.PNG)

**Comment by runout-at** [comment]
https://github.com/leibler/dokuwiki-plugin-todo/blob/master/syntax/list.php#L174
https://github.com/leibler/dokuwiki-plugin-todo/blob/master/syntax/todo.php#L164

i do not really understand why we have `([^>]*)` in the regex.
anybody here with more knowledge about regex to solve this?

**Comment by einhirn** [comment]
That part of the regex is about "match and assign to a variable anything except a '>'

**Comment by einhirn** [comment]
<todo[\s]*?.*?>(?=.*?</todo>)
match '<todo', then whitespace, non-greedy ('[\s]*?'), then anything non-greedy ('.*?'). The following is a "lookahead assertion" '(?=...)': See if it would match, but don't include in match.

**Comment by einhirn** [comment]
Had I looked at
> https://github.com/leibler/dokuwiki-plugin-todo/blob/master/syntax/list.php#L174
earlier, I would have easily spotted that the issue results from using a greedy match (`.*`) instead of a non-greedy one (`.*?`) between the todo-tags.

Anyway, fixed just now.
