### ISSUE TITLE
Checkmark does not persist

### ISSUE THREAD

**Issue by mirgcire** [leibler/dokuwiki-plugin-todo#85]
When I check a box, the checkmark appears, but when I refresh the page the checkmark is gone.
It seems to work with Linux Mint, but not Chrome or IE
If it makes any difference: I have dokuwiki hosted on Siteground server (LAMP stack)

**Comment by mirgcire** [comment]
Okay ... now it is working on Chrome.
Needless to say ... this is a little odd.
I am finding other inconsistencies as well, such as when using
"~~TODOLIST completed:no~~" on the start page
and manually placing a # symbol in a <todo> element on another page, it is not reflected in the "start" page list, no matter how many times I refresh.
However, I found that if I edit the "start" page, make any change (like add a space: " ") and save, then the change becomes reflected properly on the "start" page.

**Comment by runout-at** [comment]
do you have a `~~NOCACHE~~` on that page?
maybe try that because this looks like a caching problem to me.

**Comment by mirgcire** [comment]
That's it .... I have caching enabled on my hosting account.
Adding `~~NOCACHE~~` fixed the problem.  Thanks!
