### ISSUE TITLE
Allow empty todoinnertext

### ISSUE THREAD

**Issue by regystro** [leibler/dokuwiki-plugin-todo#88]
Hi. Thank you for this great plugin.
Please, add an option to use empty todos or at least blank ones using only a space character:

`<todo></todo>`
`<todo> </todo>`

That's useful to create tables with dynamic checkboxes to track completion. Example code:
```
^ Task     ^ Done           ^
| Task #1  | <todo></todo>  |
| Task #2  | <todo></todo>  |
```

I know that would somehow render `~~TODOLIST~~` useless, but we could filter those empty ones to be ignored or even push the envelope and try to detect those inside a table and list them adding row/column names.

Thanks so much.

**Comment by MvErven** [comment]
Yes please!

**Comment by einhirn** [comment]
https://github.com/leibler/dokuwiki-plugin-todo/blob/60db5b5d600af23c8dbcf11364ec4919b6cd957e/syntax/todo.php#L122 here is where empty todo's are getting ignored. I guess I'd add a config option and check it here. Then, when rendering the todoitem in "" I'd probably add a check whether there was any text to be shown - and thus decide whether to render the surrounding HTML...

So just implement it and send a PR. Thanks!
