### ISSUE TITLE
Multiple TODOLISTs result in blank page

### ISSUE THREAD

**Issue by OldMcWeb** [leibler/dokuwiki-plugin-todo#89]
Im playing around with the ToDo Plugin and found that:

`====== Global Wiki ======`
`~~NOCACHE~~`
`~~TODOLIST~~`
`~~TODOLIST ns:playground:todo~~`
`~~TODOLIST assigned:weber~~`

results in a blank page

Assigned doesn't seem to work with 2 todolists

**Comment by runout-at** [comment]
your example does work in my wiki installation fine.

**Comment by OldMcWeb** [comment]
Ok,

here are some more information (i should have provided them in the first place, sorry)

- Im working on Release 2017-02-19b "Frusterick Manners"

- I discovered that everithing works out finde as a "full user", i read all data from LDAP and depending on the group they are in, I let them read single tree elemets of the wiki and others not

**Comment by runout-at** [comment]
Same DW release here.
Using LDAP for user auth and groups.
Latest TODO plugin.

And it works fine.
Maybe your issue is only in combination with an other plugin which i don't use here.

**Comment by OldMcWeb** [comment]
Thanks,

I will try to disable my plugins one after the other

**Comment by OldMcWeb** [comment]
Ok, works after installing fresh out of the box
