### ISSUE TITLE
Checked <todo> but in 'disabled' state

### ISSUE THREAD

**Issue by MvErven** [leibler/dokuwiki-plugin-todo#90]
Hello. My question is; Can we have a <todo #> some text<todo>  in a disabled state?
I mean, it wil be listed in a <panel> or <modal> using bootstrap theme, while the user may not uncheck the box.

I've looked at bureaucrazy and do plugin. They can't.

**Comment by runout-at** [comment]
Users can't uncheck the box if they don't have write permission to the page.
I don't see a way to restrict the user if he has write permission to the page.
If you have an idea how to do that... tell us :)

**Comment by MvErven** [comment]
I was looking at is just as the Bootswrappers Theme <button> 
To be precise: It's a modal, where I have some <todo> in a row. Only 2 of them should be 'disabled'by design.

![2017-08-24_164258](https://user-images.githubusercontent.com/17900348/29672051-7bd5679e-88eb-11e7-8ba9-544ba538ece5.png)

**Comment by runout-at** [comment]
as i said, this looks like a permission problem which won't fix.

**Comment by MvErven** [comment]
It wasn't meant as a permission issue. Just like bootstrap to 'disable' the option to change checked state. Nevermind. I'll live with it. But Thanks for the reply.  ;)
