### ISSUE TITLE
Checkbox only "checks" once.

### ISSUE THREAD

**Issue by rogermartensson** [leibler/dokuwiki-plugin-todo#92]
Noticed a strange thing.

This is on a page with NOCACHE and multiple (10+) todo:s.

When visiting this page I can mark/unmark one checkbox. Afterwards it doesnt work. Nothing happens. If i refresh the page I can check/uncheck another box. I seem to be able to "double-click" a box which checks/unchecks it but does not get "overlined".

This is on Edge, E11 and Firefox (very new) on Windows 10. I have noticed this on on W7 install with older browsers.

**Comment by runout-at** [comment]
I can not reproduce this.
Versions of Wiki and Plugins?

**Comment by MvErven** [comment]
Overlined can be set in the extention configuration right?
I have disabled strikethrough.
![2017-08-24_103524](https://user-images.githubusercontent.com/17900348/29657478-136483a8-88b8-11e7-9789-49e433b82d28.png)

**Comment by rogermartensson** [comment]
I'm using Frusterick Manners. Not tested with 2017-02-19d.
I'm seeing this with Both Windows Edge and Firefox 55.

**Comment by runout-at** [comment]
sorry, there is no version from 2017-08-25
last commit to stable was #81 in jan. 2017
please be more precise and provide more information about this issue.

**Comment by rogermartensson** [comment]
Can't find any "version number" in the Extension Manager but according to Plugin-list I'm using a version last updated 2015-03-15. (https://www.dokuwiki.org/plugin:todo)

**Comment by rogermartensson** [comment]
I found the "problem". The real reason was in my installation where a plugin dropped a 500 on the second click on the checkbox. I noticed the error in firebug.

I added a fail-method on the jQuery.Post that shows an error instead of error in silence. 
``
			var whenError = function (data) {
				alert("Got an error while updating: " + data.statusText + " (" + data.status + ")");
			};
			
            jQuery.post(
                DOKU_BASE + 'lib/exe/ajax.php',
                {
                    call: 'plugin_todo',
                    index: param.index,
                    pageid: param.pageid,
                    checked: checked ? "1" : "0",
                    date: param.date
                },
                whenCompleted,
                'json'
            ).fail(whenError);
``

The error message can be more informational that something else in the installation (mostly plugins) is failing while trying to update the page.

**Comment by runout-at** [comment]
Would be nice if you make a pull request with this :)

**Comment by rogermartensson** [comment]
Sure. I'll try to do that. May take a little while so don't hold your breath. Need to find some spare and unused moments. :)

**Comment by rogermartensson** [comment]
I'm closing my issue since it's too old.

And I didn't do a pull request as I promised. :(
Since dokuwiki have changed a lot since 2017 I'm not sure I can reproduce.
