### ISSUE TITLE
Update not correct

### ISSUE THREAD

**Issue by rmfrankch** [leibler/dokuwiki-plugin-todo#93]
I use the extension manager to run the update. This seems to go through just fine, I get the message 'Plugin todo updated successfully', however, the plugin remains not updated claiming: 'Update: New version 2017-01-06 is available.' 

Status: installed, enabled, plugin
Download URL: github.com/leibler/dokuwiki-plu…odo/archive/stable.zip
Repository: github.com/leibler/dokuwiki-plugin-todo
Installed version: 2016-07-06
Your last update: Mon, 28 Aug 2017 11:00:58 +0200
Available version: 2017-01-06
Provides: Action, Syntax
Compatible with: "Detritus" (2015-08-10), "Hrun" (2014-09-29), "Ponder Stibbons" (2014-05-05), "Binky" (2013-12-08), "Weatherwax" (2013-05-10), "Adora Belle" (2012-10-13)
Similar to: :do

**Comment by runout-at** [comment]
I just updated the wiki.
Last commit to stable was on 2017-01-06:
https://github.com/leibler/dokuwiki-plugin-todo/commits/stable

now changed the date in stable too.
