### ISSUE TITLE
Favorites tasks

### ISSUE THREAD

**Issue by pavel-g** [leibler/dokuwiki-plugin-todo#97]
First of all, Thanks for your useful plugin.

I want propose new feature: method to easy marking favorite tasks (or high priority tasks). Currently, "favorites tasks" in the work.

I want see next to the checkbox a button for easy toggle favorite status.

I have experimentaly code with this feature. But it not ready for merging into master branch.

![favorites tasks](https://user-images.githubusercontent.com/1629593/32701948-52cff4bc-c811-11e7-9bb5-cef6e68c5079.png)

Interested you that new feature?

Sorry for my english.

**Comment by einhirn** [comment]
Send a pull request - maybe something of interest for some user.
