### ISSUE TITLE
Real user name settings shows e-mail rather than name

### ISSUE THREAD

**Issue by babudro** [leibler/dokuwiki-plugin-todo#98]
I just tried the showname:real feature for the first time and found that it gives the value of the Email field in the User Manager, rather than the Real Name field.  It does this whether I put "showname:real" in a todo tag or just rely on the default "real" setting in the configuration.

I am running the latest  2017-02-19e version of Dokuwiki.

**Comment by runout-at** [comment]
I just figured out that `userlink($username, true/false)` doesn't give the realname as stated in the docs:

https://xref.dokuwiki.org/reference/dokuwiki/nav.html?_functions/userlink.html

**Comment by runout-at** [comment]
By now, this will be controlled by the config setting 'showuseras'

https://github.com/splitbrain/dokuwiki/issues/2411

If i can find a way to get the realname of an user i'll fix this.
